restructure catalog build

diff --git a/.github/workflows/catalog_external_test2.yaml b/.github/workflows/catalog_external_test2.yaml
--- a/.github/workflows/catalog_external_test2.yaml
+++ b/.github/workflows/catalog_external_test2.yaml
@@ -40,9 +40,34 @@ jobs:
         shell: Rscript {0}
         run: source("catalog/model_metadata.R")
 
-      - name: Render catalog
+      - name: Render catalog page
         shell: Rscript {0}
-        run: source("catalog/catalog.R")
+        run: source("catalog/build_catalog_scripts/catalog.R")
+
+      - name: Render forecasts
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/forecast_models.R")
+
+      - name: Render summaries
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/summaries_models.R")
+
+      - name: Render scores
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/scores_models.R")
+
+      - name: Render noaa
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/noaa_forecasts.R")
+
+      - name: Render sites
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/build_sites_page.R")
+
+      - name: Render targets
+        shell: Rscript {0}
+        run: source("catalog/build_catalog_scripts/create_targets_page.R")
+
 
       - name: Commit and Push
         run: |
@@ -57,97 +82,144 @@ jobs:
 
 
 
-  #forecasts:
-  #  needs: metadata_catalog
-  #  if: success() || failure()
-  #  runs-on: ubuntu-latest
-  #  env:
-  #    GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-  #    EXTERNAL_GH_PAT: ${{ secrets.CATALOG_TOKEN }}
-  #    OSN_KEY: ${{ secrets.OSN_KEY }}
-  #    OSN_SECRET: ${{ secrets.OSN_SECRET }}
-  #  container:
+  # forecasts:
+  #   needs: metadata_catalog
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     EXTERNAL_GH_PAT: ${{ secrets.CATALOG_TOKEN }}
+  #     OSN_KEY: ${{ secrets.OSN_KEY }}
+  #     OSN_SECRET: ${{ secrets.OSN_SECRET }}
+  #   container:
   #    #image: eco4cast/rocker-neon4cast:latest
-  #    image: rocker/ml-verse
-  #    options: --memory 15120m
-  #  steps:
-  #    - run: git config --system --add safe.directory '*'
-#
- #     - name: checkout source repository
-  #      uses: actions/checkout@v4
-  #      with:
-  #         fetch-depth: 0
-  #         set-safe-directory: '*'
-
-#      - name: clone catalog destination repository
- #       run: |
- #         git clone --depth 1 https://github.com/eco4cast/neon4cast-catalog.git ../neon4cast-catalog
-#
-#      - name: Install
-#        shell: Rscript {0}
-#        run: |
-#          install.packages('gsheet')
-#          devtools::install_github('eco4cast/stac4cast')
-
- #     - name: Render Forecasts
- #       shell: Rscript {0}
- #       run: source('catalog/forecasts/forecast_models.R')
-
- #     - name: Commit and Push
- #       run: |
- #         cd ../neon4cast-catalog
- #         git config user.name github-actions
- #         git config user.email github-actions@github.com
-
- #         git pull
- #         git add catalog/* .
- #         git commit -a -m "update catalog" || echo "nothing to commit"
- #         git push https://${EXTERNAL_GH_PAT}:${EXTERNAL_GH_PAT}@github.com/eco4cast/neon4cast-catalog
-
-
-  summaries:
-    needs: forecasts
-    if: success() || failure()
-    runs-on: ubuntu-latest
-    env:
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      EXTERNAL_GH_PAT: ${{ secrets.CATALOG_TOKEN }}
-      OSN_KEY: ${{ secrets.OSN_KEY }}
-      OSN_SECRET: ${{ secrets.OSN_SECRET }}
-    container:
-      #image: eco4cast/rocker-neon4cast:latest
-      image: rocker/ml-verse
-      options: --memory 15120m
-    steps:
-      - run: git config --system --add safe.directory '*'
-
-      - name: checkout source repository
-        uses: actions/checkout@v4
-        with:
-           fetch-depth: 0
-           set-safe-directory: '*'
-
-      - name: clone catalog destination repository
-        run: |
-          git clone --depth 1 https://github.com/eco4cast/neon4cast-catalog.git ../neon4cast-catalog
-
-      - name: Install
-        shell: Rscript {0}
-        run: |
-          install.packages('gsheet')
-          devtools::install_github('eco4cast/stac4cast')
-
-      - name: Render Forecasts
-        shell: Rscript {0}
-        run: source('catalog/summaries/summaries_models.R')
-
-      - name: Commit and Push
-        run: |
-          cd ../neon4cast-catalog
-          git config user.name github-actions
-          git config user.email github-actions@github.com
-
-          git pull
-          git add catalog/* .
-          git commit -a -m "update catalog" || echo "nothing to commit"
-          git push https://${EXTERNAL_GH_PAT}:${EXTERNAL_GH_PAT}@github.com/eco4cast/neon4cast-catalog
+  #     image: rocker/ml-verse
+  #     options: --memory 15120m
+  #   steps:
+  #     - run: git config --system --add safe.directory '*'
+  #
+  #     - name: checkout source repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #           fetch-depth: 0
+  #           set-safe-directory: '*'
+  #
+  #     - name: clone catalog destination repository
+  #       run: |
+  #         git clone --depth 1 https://github.com/eco4cast/neon4cast-catalog.git ../neon4cast-catalog
+  #
+  #     - name: Install
+  #         shell: Rscript {0}
+  #         run: |
+  #           install.packages('gsheet')
+  #           devtools::install_github('eco4cast/stac4cast')
+  #
+  #     - name: Render Forecasts
+  #         shell: Rscript {0}
+  #         run: source('catalog/forecasts/forecast_models.R')
+  #
+  #     - name: Commit and Push
+  #         run: |
+  #           cd ../neon4cast-catalog
+  #           git config user.name github-actions
+  #           git config user.email github-actions@github.com
+  #
+  #           git pull
+  #           git add catalog/* .
+  #           git commit -a -m "update catalog" || echo "nothing to commit"
+  #           git push https://${EXTERNAL_GH_PAT}:${EXTERNAL_GH_PAT}@github.com/eco4cast/neon4cast-catalog
+  #
+  #
+  # summaries:
+  #   needs: forecasts
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     EXTERNAL_GH_PAT: ${{ secrets.CATALOG_TOKEN }}
+  #     OSN_KEY: ${{ secrets.OSN_KEY }}
+  #     OSN_SECRET: ${{ secrets.OSN_SECRET }}
+  #   container:
+  #     #image: eco4cast/rocker-neon4cast:latest
+  #     image: rocker/ml-verse
+  #     options: --memory 15120m
+  #   steps:
+  #     - run: git config --system --add safe.directory '*'
+  #
+  #     - name: checkout source repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #          fetch-depth: 0
+  #          set-safe-directory: '*'
+  #
+  #     - name: clone catalog destination repository
+  #       run: |
+  #         git clone --depth 1 https://github.com/eco4cast/neon4cast-catalog.git ../neon4cast-catalog
+  #
+  #     - name: Install
+  #       shell: Rscript {0}
+  #       run: |
+  #         install.packages('gsheet')
+  #         devtools::install_github('eco4cast/stac4cast')
+  #
+  #     - name: Render Forecasts
+  #       shell: Rscript {0}
+  #       run: source('catalog/summaries/summaries_models.R')
+  #
+  #     - name: Commit and Push
+  #       run: |
+  #         cd ../neon4cast-catalog
+  #         git config user.name github-actions
+  #         git config user.email github-actions@github.com
+  #
+  #         git pull
+  #         git add catalog/* .
+  #         git commit -a -m "update catalog" || echo "nothing to commit"
+  #         git push https://${EXTERNAL_GH_PAT}:${EXTERNAL_GH_PAT}@github.com/eco4cast/neon4cast-catalog
+  #
+  # scores:
+  #   needs: summaries
+  #   if: success() || failure()
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+  #     EXTERNAL_GH_PAT: ${{ secrets.CATALOG_TOKEN }}
+  #     OSN_KEY: ${{ secrets.OSN_KEY }}
+  #     OSN_SECRET: ${{ secrets.OSN_SECRET }}
+  #   container:
+  #     #image: eco4cast/rocker-neon4cast:latest
+  #     image: rocker/ml-verse
+  #     options: --memory 15120m
+  #   steps:
+  #     - run: git config --system --add safe.directory '*'
+  #
+  #     - name: checkout source repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #          fetch-depth: 0
+  #          set-safe-directory: '*'
+  #
+  #     - name: clone catalog destination repository
+  #       run: |
+  #         git clone --depth 1 https://github.com/eco4cast/neon4cast-catalog.git ../neon4cast-catalog
+  #
+  #     - name: Install
+  #       shell: Rscript {0}
+  #       run: |
+  #         install.packages('gsheet')
+  #         devtools::install_github('eco4cast/stac4cast')
+  #
+  #     - name: Render Forecasts
+  #       shell: Rscript {0}
+  #       run: source('catalog/summaries/summaries_models.R')
+  #
+  #     - name: Commit and Push
+  #       run: |
+  #         cd ../neon4cast-catalog
+  #         git config user.name github-actions
+  #         git config user.email github-actions@github.com
+  #
+  #         git pull
+  #         git add catalog/* .
+  #         git commit -a -m "update catalog" || echo "nothing to commit"
+  #         git push https://${EXTERNAL_GH_PAT}:${EXTERNAL_GH_PAT}@github.com/eco4cast/neon4cast-catalog
